name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ${{ secrets.SSH_PRIVATE_KEY }} \
              ubuntu@${{ secrets.EC2_HOST }} \
              "cd fastapi-book-project && \
               git fetch origin main && \
               git reset --hard origin/main && \
               source venv/bin/activate && \
               pip install -r requirements.txt && \
               python3 -m uvicorn main:app" 