name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem || exit 1
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          # SSH into EC2 and run deployment commands
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST || 'ec2-34-226-208-247.compute-1.amazonaws.com' }} << 'EOF'
            cd fastapi-book-project || exit 1
            git pull origin main || exit 1
            source venv/bin/activate || exit 1
            pip install -r requirements.txt || exit 1
            nohup python3 -m uvicorn main:app --host 0.0.0.0 --port 8000 &
          EOF
